version: "3.8"

services:

  db:
    container_name: postgres_db_test
    image: postgres:14.2
    restart: always
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=test
    volumes:
      - postgres_data_test:/var/lib/postgresql/data/
    networks:
      - postgres

  backend:
    container_name: backend_test
    user: "${UID}:${GID}"
    ports:
      - "${API_PORT}:8000"
    volumes:
      - "./backend:/app"
    environment:
      - DATABASE_URL=postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/test
      - BROKER_URL=pyamqp://${RABBITMQ_USER}:${RABBITMQ_PASSWORD}@rabbitmq3:5672
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

volumes:
  postgres_data_test:
